def create_entity_cls(
    base_cls,
    component_instance_name,
    entity_name,
    param_type_cls,
    description="",
    buffer_field="Param_Buffer",
):
    """
    Generic class factory for Adamant ID'd entities. Creates a subclass of
    base_cls (Event, Data_Product, Packet, Fault, etc.) that:

      - Accepts a typed Param/Buffer kwarg and serializes it into the base
        class's buffer field on construction
      - Decodes the buffer back into the typed parameter on deserialization
      - Pretty-prints with timestamp, component, name, ID, and decoded param

    Parameters:
      base_cls                 - The autocoded packed type base (e.g. Event, Data_Product)
      component_instance_name  - Assembly component instance name
      entity_name              - Entity name within the component
      param_type_cls           - Packed type class for the payload, or None
      description              - Human-readable description string
      buffer_field             - Name of the buffer field on base_cls
                                 ("Param_Buffer" for Event/Fault, "Buffer" for Data_Product/Packet)
    """

    # When no base class is provided (e.g. parameters), return a
    # lightweight metadata-only descriptor instead of a packed type subclass.
    if base_cls is None:
        _cin = component_instance_name
        _en = entity_name
        _desc = description
        _ptc = param_type_cls

        class EntityEntry:
            __slots__ = ()
            component_instance_name = _cin
            entity_name = _en
            description = _desc
            param_type_cls = _ptc

            def __repr__(self):
                return "%s.%s" % (_cin, _en)

        return EntityEntry

    class SpecificEntity(base_cls):
        def __init__(self, Header=None, Param=None):
            self.component_instance_name = component_instance_name
            self.entity_name = entity_name
            self.description = description
            self.has_param = False
            param_buffer = None
            if Param is not None:
                self.has_param = True
                if param_type_cls is not None:
                    assert isinstance(Param, param_type_cls), (
                        "Expected type for field 'param' to be '"
                        + str(param_type_cls)
                        + "' and instead found '"
                        + str(type(Param))
                    )
                param_buffer = list(Param.to_byte_array())
            self.Param = Param

            super(SpecificEntity, self).__init__(
                Header=Header, **{buffer_field: param_buffer}
            )

        def _from_byte_array(self, stream):
            super(SpecificEntity, self)._from_byte_array(stream)
            buf = getattr(self, buffer_field, None)
            if buf and param_type_cls is not None:
                self.Param = param_type_cls.create_from_byte_array(bytes(buf))

        def pretty_print_string(self):
            seconds = 0
            subseconds = 0
            id = 0
            param = ""
            if self.Header:
                if self.Header.Time:
                    if self.Header.Time.Seconds:
                        seconds = self.Header.Time.Seconds
                    if self.Header.Time.Subseconds:
                        subseconds = self.Header.Time.Subseconds
                if self.Header.Id:
                    id = self.Header.Id
            if self.Param:
                param = ": " + self.Param.to_tuple_string()

            if not self.Header or not self.Header.Time or self.Header.Time._size_in_bytes == 6:
                return "%010d.%06d - %s.%s (0x%04X) %s" % (
                    seconds,
                    int((subseconds / (2**16)) * 1000000),
                    self.component_instance_name,
                    self.entity_name,
                    id,
                    param,
                )
            else:
                return "%010d.%09d - %s.%s (0x%04X) %s" % (
                    seconds,
                    int((subseconds / (2**32)) * 1000000000),
                    self.component_instance_name,
                    self.entity_name,
                    id,
                    param,
                )

    return SpecificEntity


# Testing code:
if __name__ == "__main__":
    # Build our dependencies using the build system.
    # This is necessary because some of the dependencies we
    # have are autogenerated.
    from util import pydep

    pydep.build_py_deps()

    # Imports:
    import sys
    from tick import Tick
    from sys_time import Sys_Time
    from event_header import Event_Header
    from data_product_header import Data_Product_Header
    from fault_header import Fault_Header

    # ------------------------------------------------------------------
    # Test 1: Event (Param_Buffer) — matches the old event_class_generator test
    # ------------------------------------------------------------------
    tick_event_cls = create_entity_cls(
        __import__("event").Event,
        "My_Component", "The_Event", Tick, "A tick event occurred."
    )

    empty_event = tick_event_cls()
    sys.stderr.write("Event empty:  " + empty_event.pretty_print_string() + "\n")
    filled_event = tick_event_cls(
        Header=Event_Header(
            Time=Sys_Time(15, 7000), Id=10, Param_Buffer_Length=Tick()._size_in_bytes
        ),
        Param=Tick(Time=Sys_Time(15, 7000), Count=15),
    )
    sys.stderr.write("Event filled: " + filled_event.pretty_print_string() + "\n")

    # Round-trip serialization:
    empty_event.from_byte_array(filled_event.to_byte_array())
    sys.stderr.write("Event deser:  " + empty_event.pretty_print_string() + "\n")
    assert empty_event == filled_event, "Event round-trip failed"
    assert filled_event.description == "A tick event occurred."
    sys.stderr.write("Event test PASSED\n\n")

    # ------------------------------------------------------------------
    # Test 2: Data_Product (Buffer)
    # ------------------------------------------------------------------
    tick_dp_cls = create_entity_cls(
        __import__("data_product").Data_Product,
        "My_Component", "The_Dp", Tick, "A data product.", "Buffer"
    )

    empty_dp = tick_dp_cls()
    filled_dp = tick_dp_cls(
        Header=Data_Product_Header(
            Time=Sys_Time(20, 8000), Id=5, Buffer_Length=Tick()._size_in_bytes
        ),
        Param=Tick(Time=Sys_Time(20, 8000), Count=42),
    )
    sys.stderr.write("DP filled:    " + filled_dp.pretty_print_string() + "\n")

    empty_dp.from_byte_array(filled_dp.to_byte_array())
    assert empty_dp == filled_dp, "Data_Product round-trip failed"
    assert filled_dp.description == "A data product."
    sys.stderr.write("Data_Product test PASSED\n\n")

    # ------------------------------------------------------------------
    # Test 3: Fault (Param_Buffer)
    # ------------------------------------------------------------------
    # Fault buffer is smaller than Event/DP, so use Sys_Time (6 bytes) as param.
    time_fault_cls = create_entity_cls(
        __import__("fault").Fault,
        "My_Component", "The_Fault", Sys_Time, "A fault."
    )

    fault_param = Sys_Time(30, 9000)
    filled_fault = time_fault_cls(
        Header=Fault_Header(
            Time=Sys_Time(30, 9000), Id=7, Param_Buffer_Length=fault_param._size_in_bytes
        ),
        Param=fault_param,
    )
    sys.stderr.write("Fault filled: " + filled_fault.pretty_print_string() + "\n")

    empty_fault = time_fault_cls()
    empty_fault.from_byte_array(filled_fault.to_byte_array())
    assert empty_fault == filled_fault, "Fault round-trip failed"
    sys.stderr.write("Fault test PASSED\n\n")

    # ------------------------------------------------------------------
    # Test 4: Metadata-only (base_cls=None)
    # ------------------------------------------------------------------
    entry_cls = create_entity_cls(None, "My_Component", "My_Param", Tick, "A parameter.")
    assert entry_cls.component_instance_name == "My_Component"
    assert entry_cls.entity_name == "My_Param"
    assert entry_cls.description == "A parameter."
    assert entry_cls.param_type_cls is Tick
    assert repr(entry_cls()) == "My_Component.My_Param"
    sys.stderr.write("Metadata-only test PASSED\n\n")

    sys.stderr.write("All tests PASSED\n")
