name: adamant
services:
    adamant:
        image: ghcr.io/lasp/adamant:0.1
        build:
            context: .
            dockerfile: Dockerfile
            x-bake:
                platforms:
                    - linux/amd64
                    - linux/arm64
        container_name: adamant_container
        volumes:
            - type: bind
              source: ../../adamant
              target: /home/user/adamant
        network_mode: host
        extra_hosts:
            - host.docker.internal:host-gateway
        command: sleep infinity
