pragma Style_Checks (Off);
pragma Ada_2012;

with Interfaces.C;

-- Ada binding for QuatNormAlgorithm C interface
-- This would normally be generated by h2ads but created manually for this example
package Quat_Norm_Algorithm_C is
   pragma Preelaborate;

   -- Array types for quaternion components
   type Quat_Array_Type is array (0 .. 3) of Interfaces.C.C_float
     with Convention => C;

   -- Opaque handle for C++ algorithm instance  
   type Quat_Norm_Algorithm is limited private;
   type Quat_Norm_Algorithm_Access is access all Quat_Norm_Algorithm;
   
   -- POD C types
   type Quaternion_C_Type is record
      Q : Quat_Array_Type;
   end record
     with Convention => C;
   
   type Quat_Result_C_Type is record
      Q_Out     : Quat_Array_Type;
      Magnitude : Interfaces.C.C_float;
      Valid     : Interfaces.C.C_bool;
   end record
     with Convention => C;

   -- Algorithm lifecycle functions
   function Create return Quat_Norm_Algorithm_Access
     with Import => True,
          Convention => C,
          External_Name => "QuatNormAlgorithm_create";

   procedure Destroy (Self : Quat_Norm_Algorithm_Access)
     with Import => True,
          Convention => C,
          External_Name => "QuatNormAlgorithm_destroy";

   -- Core algorithm function
   function Normalize (Self  : Quat_Norm_Algorithm_Access;
                       Input : access constant Quaternion_C_Type) return Quat_Result_C_Type
     with Import => True,
          Convention => C,
          External_Name => "QuatNormAlgorithm_normalize";

private
   type Quat_Norm_Algorithm is null record;

end Quat_Norm_Algorithm_C;